# Generated by Django 5.2.2 on 2025-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foto/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
