# Generated by Django 5.2.2 on 2025-06-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='foto',
        ),
    ]
