# Generated by Django 5.2.2 on 2025-06-08 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_image_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='foto/no_foto.jpg', null=True, upload_to='foto/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
