# Generated by Django 5.2.2 on 2025-06-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_managers_suspicioususer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspicioususer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='suspicioususer',
            name='reason',
            field=models.TextField(verbose_name='Причина'),
        ),
    ]
