# Generated by Django 5.2.2 on 2025-06-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='postal_code',
        ),
    ]
