# Generated by Django 5.2.2 on 2025-06-06 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(default=1, max_length=100, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_private',
            field=models.BooleanField(default=1, verbose_name='Частный дом'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название улица')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='shop_street_name_e3f7bb_idx')],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.street', verbose_name='Улица'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
