# Generated by Django 5.2.2 on 2025-06-06 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_usersproducts_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersproducts',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
