# Generated by Django 5.2.2 on 2025-06-08 13:18

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/no_image.jpg', null=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='usersproducts',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='usersproducts',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Обзор'),
        ),
        migrations.AlterUniqueTogether(
            name='usersproducts',
            unique_together={('user', 'product')},
        ),
    ]
