# Generated by Django 5.2.2 on 2025-06-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersproducts',
            unique_together=set(),
        ),
    ]
