# Generated by Django 5.2.2 on 2025-06-09 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_category_slug_alter_product_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInCart',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='UsersProducts',
            new_name='Feedback',
        ),
    ]
