# Generated by Django 5.2.2 on 2025-06-13 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_productincart_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.street', verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
